name = "JEEFNET Vault Hunters"
author = "Jeef"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e0f47179edadec619abceeb8fba045a64e28a035aa51ac8eadcdbd41878abcf"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
