name = "JEEFNET Vault Hunters"
author = "Jeef"
version = "1.0.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c54d3057da6d88b35c0f311c6acab87adbfdaf360526b09c081dfdecab991bf6"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
