name = "JEEFNET Vault Hunters"
author = "Jeef"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "239fc3e1fa234c6f8fa8e2882c69a8a930bad3544920922cf925fa84cc64ca4b"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
